# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3ekzus9lA8O427ydYlSxlvvtkl9deTR
"""

!streamlit run app.py

import streamlit as st
import pandas as pd
import zipfile
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

# -----------------------------------------------------
# Load Data
# -----------------------------------------------------

@st.cache_data
def load_data():
    with zipfile.ZipFile("archive.zip") as z:
        with z.open("PS_20174392719_1491204439457_log.csv") as f:
            df = pd.read_csv(f)
    return df

df = load_data()

# -----------------------------------------------------
# Preprocess Data
# -----------------------------------------------------
df_model = df.copy()

# Encode categorical columns
label_cols = ["type", "nameOrig", "nameDest"]
encoders = {}

for col in label_cols:
    enc = LabelEncoder()
    df_model[col] = enc.fit_transform(df_model[col])
    encoders[col] = enc

X = df_model.drop(["isFraud", "isFlaggedFraud"], axis=1)
y = df_model["isFraud"]

# Train model
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# -----------------------------------------------------
# Streamlit Interface
# -----------------------------------------------------

st.title("💳 Fraud Detection App")
st.write("Enter transaction details to predict whether it's fraud.")

# User inputs
step = st.number_input("Step (1–744)", min_value=1, max_value=744, value=1)

type_input = st.selectbox("Transaction Type", df["type"].unique())

amount = st.number_input("Amount", min_value=0.0, value=100.0)

oldbalanceOrg = st.number_input("Old Balance (Origin)", min_value=0.0, value=0.0)
newbalanceOrig = st.number_input("New Balance (Origin)", min_value=0.0, value=0.0)

oldbalanceDest = st.number_input("Old Balance (Destination)", min_value=0.0, value=0.0)
newbalanceDest = st.number_input("New Balance (Destination)", min_value=0.0, value=0.0)

nameOrig = st.text_input("Origin Account (anything is allowed)", "C1231006815")
nameDest = st.text_input("Destination Account (anything is allowed)", "M123456789")

# Convert inputs the same way as training
if st.button("Predict Fraud"):
    # Encode user input
    row = pd.DataFrame({
        "step": [step],
        "type": [encoders["type"].transform([type_input])[0]],
        "amount": [amount],
        "nameOrig": [encoders["nameOrig"].transform([nameOrig])[0]
                     if nameOrig in encoders["nameOrig"].classes_
                     else 0],
        "oldbalanceOrg": [oldbalanceOrg],
        "newbalanceOrig": [newbalanceOrig],
        "nameDest": [encoders["nameDest"].transform([nameDest])[0]
                     if nameDest in encoders["nameDest"].classes_
                     else 0],
        "oldbalanceDest": [oldbalanceDest],
        "newbalanceDest": [newbalanceDest],
        "isFlaggedFraud": [0],
    })

    prediction = model.predict(row)[0]
    proba = model.predict_proba(row)[0][1]

    if prediction == 1:
        st.error(f"⚠️ Fraud Detected! (Probability: {proba:.2f})")
    else:
        st.success(f"✅ Not Fraudulent (Probability fraud: {proba:.2f})")

!wget https://raw.githubusercontent.com/manishguptads/Fraud-Detection/main/archive.zip

!pip install streamlit